import React from 'react'
// 👨‍✈️ Spécification : Notre application doit supporter les thèmes `clair/sombre`

// 🐶 Nous avons déjà les imports de base, mais il nous manque un élément important
// 🐶 Tu dois importer le `ThemeProvider` depuis `@/components/theme-provider`
import type {Metadata} from 'next'
import {Geist, Geist_Mono} from 'next/font/google'
import './globals.css'
import {ThemeProvider} from '@/components/theme-provider'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    // 🐶 Première étape : Ajoute l'attribut `suppressHydrationWarning` à la balise html
    // pour éviter les avertissements lors du changement de thème
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* 🐶 Deuxième étape : Enveloppe le contenu dans un `ThemeProvider` */}
        {/* 🤖 Le `ThemeProvider` doit avoir les propriétés suivantes :
            - attribute="class" (pour gérer les thèmes via les classes CSS)
            - defaultTheme="dark" (thème par défaut)
            - enableSystem (pour supporter les préférences système)
            - disableTransitionOnChange (pour de meilleures performances)
        */}
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
